### ISSUE TITLE
Tutorial 4 updates

### ISSUE THREAD

**Issue by a-kong** [UBC-DSCI/dsci-310-student#42]
- [x] R projects
- [x] clearing renv from home directory
- [x] update tutorial 4 repos (aka accept PR)

**Comment by chendaniely** [comment]
issue fixed with

d601483d755de148636400a90008b87c1561e5f5
30f551a147113e62bebd3459ec2b055802f3d574
7e79cfb4ce3c738effae6b3670282725010bb25f
